apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:lubY3Ljp5X1Est6vPvyaJzX2SnO4HLLqbs4kKjT8GGmR8WoNo3yLA2voqI58QWcuALffyUOQwWg7NtFwDIi5YSMeiUwgMe2RdHAJiN3BIXtT4nTmOQ9Pa7xu5xEE986ozsY0d0OAYHDGTGIWVCaZ1npPWVBNxBdCeN94XqIjbK8JnUpg8ZM7wvdvyTvh2wkM9lUGIHLKWWqXjh09/+KUHhozQWDCE7WKa6xaGM9aRU/C55jCAIeeEKTI7cISWOYeFeiuMN6GIFPlsS7bpr42iIbbBK9Nz9fSaXpBX93arpZ+Z+MpuWMSckgelZM=,iv:IN7WZ/Jstk2sko4Es19k7SX6z/J9sY8bBJyvbvpewA0=,tag:ohcqS1Ur5toXMxCSsQ+DxA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSWtRRDdKZThycERWMUtP
            aGZSMldlREYwM3VRck8zL1NOOUlHd3I2MUFJCmZWTGpFTWNrR3dySkM3Zmg5TXkv
            L3hrcU1OWmZvY0xnNjIrMXlFeGdYZDAKLS0tIGFkVGFBNzJEbUdaaHFGSHZVOGF5
            azRYbU1SaDZscC9MZjFyNm9iMzZaYU0Kx2puMuTzLhgSOIqJ1huhEWmvSLXYzSOR
            o+MTmis1NcyMFeDvvMWjIp595MijwxRgROy3fDVHR+BpgSbQkrHSZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1527r4t30z72agrkt6kksgj4rwsch8wv7hcurtw2rm4pz56v6pvyqrukkmv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T15:16:27Z"
    mac: ENC[AES256_GCM,data:kFny1vUDal0L6CwQsCR/qL+GnNiTfrTtJx06V8BPHqjeVz6GRXADFJc6PRxMyhuXe+q40W2ZlTabRKdk0YAg3lKPY8mFykF+vGWG3lTya1VEG0QAlLd+4vBI+UGCdgtzB5LWz8OwQPhock3g+0DivMmcDhQRVSqNbOBObaWmtLA=,iv:KERVRnqtoClWTd5sreeqL/LjmtRzecDOLbYROTkl5vg=,tag:I+HypTWrPQHMCu3LcdGYfw==,type:str]
    version: 3.13.1
