apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:9fjg4vtC4VobX346kPL5vjHAl1oWheuO6DKHFmvHo8Q9UF885zdDx+kv1t1+fJ3uUneQbR9pjsWRbj9J4aTtHGj44TA2mBKGMflDgg00NGWC7zSdGLxcIniF2caQ04tZ3um3YncmSKSqQ8jAja6MzRlfpSaA/N2qMsIvToAoJgl8T6Sx/RM8n6cIQz9C9L0zIqpgmSMT8k5/aW1C3npRWLmsrzzQy216hF1khKwxiU6t3pMGMKGVIdthNg/LG/etpPl+6h5qk8MIsVmIgF6BIwg7D3VznmKHjcari+VNtx6AFg0Qa0aKDRjeemI=,iv:BYpjMOynxpLQSkesSCXrWC5i2TD/gi2snS3rOROaNY0=,tag:m3hjrDNL2PNVYrYd0AL0qA==,type:str]
kind: Secret
metadata:
    name: audiobooks-tunnel
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArelZXdHdkcHdxZFBUQ2Yy
            QW83ck1OSWJ3ak1TOGQvbFVla3M2UmxLelVFCnMvcWpxZGRWcmlQb29XdCsyci93
            a2Rkcmx4QzMvVFBvdFI4RnJSeGlBQ0kKLS0tIEZWeHBuY0JZWXRxRndRK3p5c2hY
            WVdOYjd5UWtpNkZ6Q0krUVpSTDY3REEKmjjV75swOfhXy9aZlzYaYXQKMEyKv56K
            K7Di5klUHiAhxZp4QNl38jY3vokg2eu5QKARRE9XucmoXs+C9XI2wg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1527r4t30z72agrkt6kksgj4rwsch8wv7hcurtw2rm4pz56v6pvyqrukkmv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T11:47:25Z"
    mac: ENC[AES256_GCM,data:dnz+IjLfREZW4lm89YkpLjgay1i3NdO7lmvg6ApbmtCHZnke2Ce8QUv3uRA9RrC1SLXljaFsXCMPK2tT0W+rHLkSuj1xHhHxkFxGZk6TGRDMkbakO+Wyzz+wkm99I2LZVNPT8+S2V7+yqjajrx6nT0qGm5SbrmncoXCqsjZ9D40=,iv:eznv1jdt4hGNP3USWApArFa4xIwM5d6UdNqXX6E6OAE=,tag:bUAmpQDIBncI+N9s8FCeXw==,type:str]
    version: 3.13.1
