apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:MIK1Oygu1EqTzagFl3nJWbkFa7qvcx0dIIQw0OogXN7rhvWsB4T7jVVzPBQhdGMXUZBWPmjP5233AtLXZuP8hl7sLsFpNps8eacZqmGmQCsaUXGjB3ghgSxo6T2ToX90UJznMOJgY3S8KCOv0dszFbDYkZ+WOHvP5ZJNDZrYxfVdvtqUvy2KD6yklg67d0tjYvJKN8svFts4rlpH46t+0rDOYkEy5zwHHXoAGDhW7+mDGnBl2x/U9hks27BrD6GQIrsvlNB4+GHoKbm0IDbYgy8wMuFe3UNCFmPezGWZunVLRVaLpUZaUxMcvaQ=,iv:13zA4LRgWhktaSgcRWqojQSPEdmujSrO11D/mu2uiKM=,tag:b+vG5aayF0U8CfxVPVVpGg==,type:str]
kind: Secret
metadata:
    name: fogos-tunnel
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZlNBUjJyRXpRenF3Z3Y1
            NVpLRVQ1bTBGZVFjMVdxelNmS3ZLejFJMEFFCmN3Z28rbVJEcGE5L29yd2J4dVVi
            eHd6aXFLL2c2bFJydElEVUIwWEpya1kKLS0tIFR0Y0w1cXh3TytZZFh4Z1RHSWJy
            b0M1Q09ic0sreDdLc252dEthWVJ2QkUKbwfhB2LVjpLgIHWpKF/s85CPZgnY1wT6
            X3EsvEGULDl4PC8nD8CNUo7K4ZnlbG9YTcYgA0G4P337Av+6xWJoIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1527r4t30z72agrkt6kksgj4rwsch8wv7hcurtw2rm4pz56v6pvyqrukkmv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T11:03:50Z"
    mac: ENC[AES256_GCM,data:rHEVqSYRH94t6jNKTDn5xkYibOxpSUr4d0PtrXApDrWenWTipxMSpwcGspPoGPFQY69VDyMCA/GUC9XrJKgpmXotrWUxdYsWdPSG9NNVm7mxYUUBWcuhDFgyIpBdqCU/hxaBoeitQnZw5oSZ3SM+ajmtIgdhxdNHMFO5AWBjYyI=,iv:w30NseDxKFXUd47xdpA2TXgfe59nYZPDsTLhfi0322s=,tag:qhrzwrNkezRrG3JRlp1Yaw==,type:str]
    version: 3.13.1
