apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:eIUoldC/0SKCxP1zuOxQmbrev1UKH+YiE/n4O/xw+x5M5wqrVIq8tzDaLxMVCEC4U+76j+0hSwN9oWtVo4HWn1ctgrHICJWCIpswUTXwDw4jpLjnEez2RyddegCRV/m4I1WRB4nK3teRIB1H/6xqnzq6Cn5JSX7nHcrWrVzHDs9PBr0Kk50SqOtPvH5ybRtHNfv2q5he+BE4V6lzymGO5OXU62QkwRaLDJn7SyMm6ARmyZsdx5P2+wRQWheQ4zqH5cCgAMiHUIbXLcveQGa5H2PklidG0JvgJ2cg2xqQyFo3eDdq+pzL+FZnjVs=,iv:8/xC3mN0dl9IAlt+4I5XOazg9RTMMB/dlrnGM52e2do=,tag:1Ro+64BwB85UWZ96bU1U8Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-tunnel
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYY045L0lmR3cxMENFOFd2
            SjlTdXhvNFk2eFNSa0xzeCtmZlhWZk9FcFg0CnRGNFFuNkgxbVB5NU9FVVNHRHR3
            NjVMd2Y5NjA0QUpkOFVMeTVsSTU5aE0KLS0tICtWNkZNR2JuSkZ5aE5vVEZTVUht
            QXhKR2orTTdyN3JRdW5TODZDSFlwMWsKVcWZHvwWH7zYafn9kjBnzbAnD8h0hYKG
            x9ERzuMfSkdfReYq7EkGeUd6jVGN+q4clIlTXgHUUm2c85QpOXuRUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1527r4t30z72agrkt6kksgj4rwsch8wv7hcurtw2rm4pz56v6pvyqrukkmv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T15:50:12Z"
    mac: ENC[AES256_GCM,data:pIdf5Xyr2dacHk7R1To0yU5bs4ayW593FycJGQX6pusPLDpyxiby+qyCZ6gneHZ4mR1kmBz88Tn/44nv/75JvJFam2FQNBdBh2oqvCVOGn812nOgC2cxWynTBiwL63RD9+1VoCWKjP0qDuxXPvJ6SgNDBvdzvSafujl/7RYF5DQ=,iv:59yRtOGZMVuxw88cobReDHyBARWDfwU1JzujE4zl6XY=,tag:IvVQCZ/EE9DI6l5VsoPgZg==,type:str]
    version: 3.13.1
