apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:tuVlnTQlO7xbTMGlXiTaWHjWg/Y=,iv:mlO0T93S+ADWXbLVQhRJTHD8rgM/ywCF6TPfd7erkZk=,tag:k5xv7n7EXOD18ZDHc5qbbg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaanVqMmIvVHVTQWcydmsz
            SkxuajRKa2YzdW5LMlBPdTBkVnZDRTFDV0RFCmd1dnVxTUtwZ1ZHTmZIdzFXZXcv
            N1VyTk14eDZtaElCdEtVbGtScDd6YncKLS0tIHY3V2lzVEYvaDZiMTNqNmFvNVgx
            R09Vc3dGRjFCU2ppYVo0TU8yZVZaZmcKKvGFfjaU0Shxyuc7XcNAED5hPT/1ebEq
            OnELzYvQtgT3RoJC/MltVruf71nr5qhPHyoIQ4p81cpCR27pe5q6LQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1527r4t30z72agrkt6kksgj4rwsch8wv7hcurtw2rm4pz56v6pvyqrukkmv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T10:44:52Z"
    mac: ENC[AES256_GCM,data:NqJgOwZljm3n4Y2XuUb3+BT/cSyH7HSD/yvlTFvKoxJUknRT9tGpWppTkRT+Wnl++6pn9FPIH+hX7jssTpp0IBJ0sVDzUMCBcLHduxFneS7yfdBF33b/STGFAPcbvCu4qcnwh1SX1SYjWjhv4Rb2MZ4ZQGSi0R2AUP40Vuxf5AA=,iv:IbNRHKNNlXbJunYcFiuNuFSLOJtiL/US0kObOQbFRb8=,tag:Crt57PA9OEufBwX/H7pmdw==,type:str]
    version: 3.13.1
