apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:utPs2/HkfQrKN0iBgb46AQaVUBWXXJdXsyfwmEM1ZaE=,iv:Xwvt2WaZmLfgCKD3mMPJRYlwkf/z/XaS6bsooaEohhA=,tag:tMYTVJbGA9dMYoyN0U7s7g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaanVqMmIvVHVTQWcydmsz
            SkxuajRKa2YzdW5LMlBPdTBkVnZDRTFDV0RFCmd1dnVxTUtwZ1ZHTmZIdzFXZXcv
            N1VyTk14eDZtaElCdEtVbGtScDd6YncKLS0tIHY3V2lzVEYvaDZiMTNqNmFvNVgx
            R09Vc3dGRjFCU2ppYVo0TU8yZVZaZmcKKvGFfjaU0Shxyuc7XcNAED5hPT/1ebEq
            OnELzYvQtgT3RoJC/MltVruf71nr5qhPHyoIQ4p81cpCR27pe5q6LQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1527r4t30z72agrkt6kksgj4rwsch8wv7hcurtw2rm4pz56v6pvyqrukkmv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T10:05:25Z"
    mac: ENC[AES256_GCM,data:IOqPoQW1au/IGiFu9IxHoI+BISI5dM5A+4VQb91nUrtQIwHTGxr43sCSO/5CiItnsOLSBrJ8wlzZsavDZfmKt/6aPgu7d1BRAzGaXoHOQ+tVHZRvIl5tkm/w3njekYtBpFK1jHPhyRIopEXOmYz9ZhGm5LT+vLAZ6qR2/kBpnm8=,iv:maXt/EHxL4/sFyYn1rffr4JSQzA9qgjj4qyAkjYBEj8=,tag:SeIckbNNa7/q5zHovToFEg==,type:str]
    version: 3.13.1
